@extends('layout.template')

@section('content')
<table class="table table-striped">
    <thead>
        <tr>
           <th>No</th>
           <th>Nama</th>
           <th>NIM</th>
           <th>Kelas</th>
        </tr>
    </thead>
    <body>
        <tr>
            <td>1</td>
            <td>Shaqurra</td>
            <td>23/520668/SV/23277</td>
            <td>B</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Regita</td>
            <td>23/520668/SV/23275</td>
            <td>B</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Bella</td>
            <td>23/520668/SV/23278</td>
            <td>B</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Caca</td>
            <td>23/520668/SV/23267</td>
            <td>C</td>
        </tr>
    </body>
</table>

@endsection
